import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>桌面歌词</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={styles.title}>Hi! Welcome to my music space &darr;</h1>
        <div className={styles.grid}>
          <Link href={'/music'}>
            <a className={styles.card}>
              <h2>每日推荐 &rarr;</h2>
              <p>🎵每日都有新发现</p>
            </a>
          </Link>
          <Link href={"/music"}>
            <a className={styles.card}>
              <h2>私人雷达 &rarr;</h2>
              <p>🔭懂你的才是最好的～</p>
            </a>
          </Link>
          <Link href={'/music'}>
            <a className={styles.card}>
              <h2>心动模式&rarr;</h2>
              <p>💗今天你心动了吗</p>
            </a>
          </Link>
          <Link href={'/music'}>
            <a className={styles.card}>
              <h2>新歌速递 &rarr;</h2>
              <p>🆕可以听最新的歌曲了!</p>
            </a>
          </Link>
        </div>
      </main>
    </div>
  );
}
