import Head from "next/head";
import Link from "next/link";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Login() {
  const [state, setstate] = useState([]);
  return (
    <div className={styles.container}>
      <Head>
        <title>扫码登录</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h2>手机app扫码登录更安全哦</h2>

        <div className={styles.grid}>
          <a className={styles.img}>
            <img src="https://music.163.com/login?codekey=b158cfb9-9359-43e1-aae8-5658b988be0d"></img>
          </a>
        </div>
      </main>
    </div>
  );
};