import Head from "next/head";
import axios from "axios"
import { useEffect, useCallback, useRef, useState } from "react";
import styles from "../styles/Home.module.css";

export default function Music() {

    useEffect(async () => {
        let res = await axios.get('/api/recommend')
        console.log(res);
    }, []);

    return (
        <div className={styles.container}>
            <Head >
                <title>当前播放</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h2>心动模式</h2>
            </main>
        </div>
    )
}