
import Head from "next/head";
import axios from "axios"
import { useEffect, useState, useRef } from "react";
import styles from "../../styles/Home.module.css";
import { useRouter } from 'next/router';
import AppBar from "../../components/app-bar"
import styled from "styled-components"
import { Play } from 'react-feather'


const App = styled.main`
margin: 0 2rem;
max-width: 60rem;
`
const ContentContainer = styled.div`
  display: grid;
  gap: 1.25rem 1rem;
  grid-template-columns:1fr 1fr;
  @media (min-width: 768px) {
    grid-template-columns: 1fr 1fr 1fr 1fr 1fr ;
    gap: 1rem 1.2rem;
  }
`

const Playbtn = styled(Play)`
    position: absolute;
    left: 0;
    top: 0;
    z-index: -999;
    color: #222;
    border-radius: 50%;
    padding: 12px 10px 12px 14px;
    margin: 12px;
`
const Name = styled.div`
    position: absolute;
    left: 10px;
    top: 125px;
  font-weight: 500;
  font-size: 15px;
  line-height: 16px;
  margin-top: 2px;
  @media (min-width: 768px) {
    font-size: 13px;
  }
  /* overflow: hidden; */
  margin-right: 12px;
  color: #fff;
`
const Artist = styled.div`
 position: absolute;
    left: 10px;
    bottom: 10px;
  font-weight: 500;
  font-size: 12px;
  line-height: 15px;
  color: #a7a7a9;
  margin-top: 2px;
  overflow: hidden;
  margin-right: 12px;
`
const BlockSong = styled.div`
    border-radius: 1rem;
    position: relative;
    display: block;
    background:  linear-gradient(to top, rgb(42, 85, 91), rgb(57, 116, 124));
    text-decoration: none;
    color: inherit;
    width:100%;
    height: 100%;
    &:hover ${Playbtn}{
      z-index: 1    ;
      background: hsla(0, 0%, 96%, 1);
    color: hsla(240, 68%, 5%, 1);
    opacity: 0.8;
    backdrop-filter:blur(0.1)
  }
`



const ArtWork = styled.img`
  border-radius: 0.7rem;
  width: 70%;
  border: 0.3rem solid hsl(0, 0%, 0%, 0.04);
  margin: 0.375rem 3rem 3rem 0.375rem;

  min-width: 50%;
  aspect-ratio: 1;
  @media (min-width: 768px) {
    border-radius: 0.7rem;
  }
`








export default function Music() {
  const router = useRouter()
  const { id } = router.query

  const [song, setSong] = useState([]);

  const audioRef = useRef(null);

  const handleClick = async (id) => {
    console.log(id);
    let songurl = await axios.get(`/song/url?id=${id}`)
    const url = songurl.data.data[0]?.url
    console.dir(audioRef.current);
    audioRef.current.src = url;
    audioRef.current.play();
  }


  useEffect(async () => {
    if (id !== undefined) {
      let res = await axios.post(`/playlist/track/all/${id}`)
      setSong(res.data.body.songs)
      console.log(res.data.body.songs);
    }
  }, [id]);

  return (
    <div className={styles.container}>
      <Head >
        <title>歌曲列表</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <App>
        <AppBar url='/album' />
        <h2>歌曲列表</h2>
        <ContentContainer>
          {
            song.map((item) => {
              return (
                <BlockSong key={item.al.id} onDoubleClick={() => handleClick(item.id)}>
                  <audio ref={audioRef}></audio>
                  <ArtWork src={item.al.picUrl} />
                  <Playbtn size={48} />
                  <Name>{item.al.name}</Name>
                  <Artist>{item.ar[0]?.name}</Artist>
                </BlockSong>
              )
            })
          }
        </ContentContainer>

      </App>

    </div >
  )
}