import Head from "next/head";
import axios from "axios"
import { useEffect } from "react";
import styles from "../../styles/Home.module.css";
import { useRouter } from 'next/router';


export default function Music() {

    const router = useRouter();
    const { id } = router.query;
    console.log(id);
    useEffect(async () => {
        let res = await axios.post(`/playlist/track/all?id=${id}&limit=30&offset=0`)
        console.log(res.data);
    }, []);

    return (
        <div className={styles.container}>
            <Head >
                <title>歌曲列表</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 className={styles.title}><a>歌曲列表</a></h1>

            </main>
        </div>
    )
}