/*
 * @Author: Sam Zhao
 * @Date: 2022-01-17 23:27:16
 * @LastEditTime: 2023-02-11 14:01:26
 * @LastEditors: Sam Zhao
 * @Description: 
 * Copyright 2023 Sam Zhao, All Rights Reserved. 
 */
import Head from "next/head";
import axios from "axios"
import { useEffect, useCallback, useRef, useState } from "react";
import Cookies from 'js-cookie'
import styles from "../../styles/Home.module.css";
import Album from "../../components/block-music"
import AppBar from "../../components/app-bar"
import styled from "styled-components"

const ContentContainer = styled.div`
  display: grid;
  gap: 1.25rem 1rem;
  grid-template-columns: 1fr 1fr;
  @media (min-width: 768px) {
    grid-template-columns: 1fr 1fr 1fr;
    gap: 2rem 1.2rem;
  }
`
const App = styled.main`
margin: 0 2rem;
max-width: 42rem;
`
export default function Music() {
    const [albums, setAlbums] = useState([]);

    useEffect(async () => {
        let res = await axios.post(`/personalized`, { "cookie": Cookies.get('musicCookie') })
        console.log(res.data.body.result);
        setAlbums(res.data.body.result)
    }, []);

    return (
        <div className={styles.container}>
            <Head >
                <title>推荐歌单</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <App>
                <AppBar url={'/'} />
                <h2>推荐歌单</h2>
                <ContentContainer >
                    {albums.map(item => (
                        <Album
                            key={item.id}
                            url={item.picUrl}
                            name={item.name}
                            id={item.id}
                        />
                    ))}
                </ContentContainer>
            </App >
        </div >
    )
}

